### ISSUE TITLE
Need to add the `date` to the Datachats

### ISSUE THREAD

**Issue by bramj** [datacamp/datachats-content#2]
The datachats app support a field called `date` which functions as the date of publication. The default ordering is based on this `date` field, with a fallback to the `created_at` date.

I saw the last commit by @filipsch re-created the first datachat resulting in it being pushed to the top of the list: https://www.datacamp.com/datachats/

There should be a `date` set on all datachat yamls. @gor181 can you confirm that this field is supported on your side?

**Comment by gor181** [comment]
@bramj it is supported here => https://github.com/datacamp/teach-app/blob/e7b44de3110e30dda0dc5d6181a2aa08b7f6e082/app/src/enrichers.rb#L769 

But I didn't see it used in the datachats yml files yet.
